spring.application.name=Smart-Travel-Tourism

spring.datasource.url=jdbc:mysql://localhost:3306/smart_travel
spring.datasource.username=root
spring.datasource.password=778100

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000

server.port=8080